export const SHOW_LIST_REQUEST = 'SHOW_LIST_REQUEST'
export const SHOW_LIST_SUCCESS = 'SHOW_LIST_SUCCESS'
export const SHOW_LIST_FAIL = 'SHOW_LIST_FAIL'

export const SHOW_DETAILS_REQUEST = 'SHOW_DETAILS_REQUEST'
export const SHOW_DETAILS_SUCCESS = 'SHOW_DETAILS_SUCCESS'
export const SHOW_DETAILS_FAIL = 'SHOW_DETAILS_FAIL'
