export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGIN_LOGOUT = 'USER_LOGIN_LOGOUT'

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

export const USER_OTHER_INFO_REQUEST = 'USER_OTHER_INFO_REQUEST'
export const USER_OTHER_INFO_SUCCESS = 'USER_OTHER_INFO_SUCCESS'
export const USER_OTHER_INFO_FAIL = 'USER_OTHER_INFO_FAIL'

export const USER_FOLLOW_REQUEST = 'USER_FOLLOW_REQUEST'
export const USER_FOLLOW_SUCCESS = 'USER_FOLLOW_SUCCESS'
export const USER_FOLLOW_FAIL = 'USER_FOLLOW_FAIL'

export const USER_UNFOLLOW_REQUEST = 'USER_UNFOLLOW_REQUEST'
export const USER_UNFOLLOW_SUCCESS = 'USER_UNFOLLOW_SUCCESS'
export const USER_UNFOLLOW_FAIL = 'USER_UNFOLLOW_FAIL'
